

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

import torch
from PIL import Image
from transformers import AutoProcessor, Qwen3VLForConditionalGeneration


HF_REPO_ID = "vcl-iisc/DynEval-Evaluator"
HF_SUBFOLDERS = {
    "2b": "DynEval-2B",
    "4b": "DynEval-4B",
}

T2IA_ELEMENT_SYSTEM = """Given an aigc prompt, extract the elements that are important for generating images.
Classify each element into a type (object, human, animal, food, activity, attribute, counting, color, material, spatial, location, shape, other).
Examples are as follows, where Elements is in json format.

Prompt: A man posing for a selfie in a jacket and bow tie.
Elements: ["man (human)", "selfie (activity)", "jacket (object)", "bow tie (object)", "posing (activity)"]

Prompt: A horse and several cows feed on hay.
Elements: ["horse (animal)", "cows (animal)", "hay (object)", "feed on (activity)", "several (counting)"]"""

T2IA_SINGLE_QUESTION_SYSTEM = """Given a prompt for image generation and one of its related elements, generate one easy Yes/No question to verify whether the element is represented in the image generated by the prompt.
The question must be answerable by inspecting the image.
Return only JSON with exactly these keys: "question" and "answer".
The answer should be "yes" unless the element explicitly describes an absence or zero count."""

EVALUATION_SYSTEM = """You are a strict visual evidence evaluator. Your job is to test for image-text alignment by looking at the image and answering the questions respectively.
CRITICAL RULES:
1. Score based ONLY on what you can SEE in the image, not what the prompt says should be there.
2. Do NOT assume elements exist just because the prompt mentions them. Look at the actual pixels.
SCORING SCALE:
  5 = YES, DEFINITELY | 4 = YES, PROBABLY | 3 = UNCERTAIN | 2 = NO, PROBABLY | 1 = NO, DEFINITELY
Return ONLY a JSON array."""


def json_dumps(value: Any) -> str:
    """Serialize Python objects as readable UTF-8 JSON."""
    return json.dumps(value, ensure_ascii=False, indent=2)


def strip_code_fence(text: str) -> str:
    """Remove Markdown code fences that models sometimes wrap around JSON."""
    text = (text or "").strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()
    return text


def parse_first_json(raw: str) -> Any:
    """Extract the first valid JSON object or array from a raw model response."""
    text = strip_code_fence(raw)
    if not text:
        return None
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    decoder = json.JSONDecoder()
    for opener in ("[", "{"):
        start = text.find(opener)
        while start >= 0:
            try:
                parsed, _ = decoder.raw_decode(text[start:])
                return parsed
            except json.JSONDecodeError:
                start = text.find(opener, start + 1)
    return None


def normalize_key(text: str) -> str:
    """Normalize text for case-insensitive duplicate detection."""
    return re.sub(r"\s+", " ", str(text).strip().lower())


def dedupe_strings(items: list[str]) -> list[str]:
    """Keep string items in original order while removing normalized duplicates."""
    out = []
    seen = set()
    for item in items:
        item = str(item).strip()
        key = normalize_key(item)
        if key and key not in seen:
            seen.add(key)
            out.append(item)
    return out


def dedupe_questions(items: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Remove duplicate element/question pairs and normalize yes/no answers."""
    out = []
    seen = set()
    for item in items:
        if not isinstance(item, dict):
            continue
        question = str(item.get("question", "")).strip()
        element = str(item.get("element", "")).strip()
        answer = str(item.get("answer", "yes")).strip().lower()
        key = (normalize_key(element), normalize_key(question))
        if question and key not in seen:
            seen.add(key)
            out.append({"element": element, "question": question, "answer": "no" if answer.startswith("no") else "yes"})
    return out


def parse_elements(raw: str) -> list[str]:
    """Parse the <T2IA> element-extraction response into a clean element list."""
    parsed = parse_first_json(raw)
    if isinstance(parsed, list):
        return dedupe_strings([str(item) for item in parsed if str(item).strip()])
    if isinstance(parsed, dict):
        for key in ("elements", "Elements"):
            if isinstance(parsed.get(key), list):
                return dedupe_strings([str(item) for item in parsed[key] if str(item).strip()])
    return dedupe_strings(re.findall(r'"([^"]+\([^()]+\))"', raw or ""))


def parse_question(raw: str, element: str) -> dict[str, str] | None:
    """Parse one generated question for a specific element."""
    parsed = parse_first_json(raw)
    if isinstance(parsed, dict):
        question = str(parsed.get("question", "")).strip()
        answer = str(parsed.get("answer", "yes")).strip().lower()
        if question:
            return {"element": element, "question": question, "answer": "no" if answer.startswith("no") else "yes"}
    match = re.search(r"(?:Q:|Question:)\s*(.+?)(?:\n|$)", raw or "", re.IGNORECASE)
    if match:
        return {"element": element, "question": match.group(1).strip(), "answer": "yes"}
    return None


def normalize_score(value: Any) -> int:
    """Convert a model score to an integer in [1, 5], or 0 if invalid."""
    try:
        score = int(round(float(value)))
    except (TypeError, ValueError):
        match = re.search(r"\b([1-5])\b", str(value))
        score = int(match.group(1)) if match else 0
    return score if 1 <= score <= 5 else 0


def parse_answers(raw: str, questions: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Parse <EVALUATION> scores and align them with the generated questions."""
    parsed = parse_first_json(raw)
    if isinstance(parsed, dict):
        parsed = parsed.get("answers", parsed.get("scores", parsed))

    out = []
    if isinstance(parsed, list):
        for idx, question in enumerate(questions):
            item = parsed[idx] if idx < len(parsed) else {}
            if isinstance(item, dict):
                score = normalize_score(item.get("score", item.get("answer", 0)))
                reasoning = str(item.get("reasoning", "")).strip()
            else:
                score = normalize_score(item)
                reasoning = ""
            out.append({"question": question["question"], "reasoning": reasoning, "score": score})
        return out

    fallback_scores = [int(match) for match in re.findall(r"\b([1-5])\b", raw or "")]
    for idx, question in enumerate(questions):
        out.append({"question": question["question"], "reasoning": "", "score": fallback_scores[idx] if idx < len(fallback_scores) else 0})
    return out


def resolve_task_token(tokenizer, base: str) -> str:
    """Support both local-training tokens and HF-card pipe tokens.

    Local experimental checkpoints used <T2IA>/<IQA>/<EVALUATION>.
    The public HF card documents <|T2IA|>/<|IQA|>/<|EVALUATION|>.
    We choose whichever is registered as a single tokenizer token.
    """
    candidates = [f"<|{base}|>", f"<{base}>"]
    for token in candidates:
        token_id = tokenizer.convert_tokens_to_ids(token)
        encoded = tokenizer.encode(token, add_special_tokens=False)
        if len(encoded) == 1 and encoded[0] == token_id:
            return token
    return candidates[0]


def build_element_messages(token: str, prompt: str) -> list[dict[str, Any]]:
    """Build the chat messages for extracting visual elements from a prompt."""
    return [
        {"role": "system", "content": [{"type": "text", "text": T2IA_ELEMENT_SYSTEM}]},
        {"role": "user", "content": [{"type": "text", "text": f"{token}\nPrompt: {prompt}\nElements:"}]},
    ]


def build_question_messages(token: str, prompt: str, element: str) -> list[dict[str, Any]]:
    """Build the chat messages for generating one yes/no question per element."""
    user_text = f'{token}\nDescription: {prompt}\nElement: {element}\nReturn JSON:\n{{"question": "...", "answer": "yes/no"}}'
    return [
        {"role": "system", "content": [{"type": "text", "text": T2IA_SINGLE_QUESTION_SYSTEM}]},
        {"role": "user", "content": [{"type": "text", "text": user_text}]},
    ]


def build_evaluation_messages(token: str, questions: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Build multimodal chat messages for scoring generated questions on an image."""
    questions_text = "\n".join(f'{idx + 1}. Question: {item["question"]}' for idx, item in enumerate(questions))
    user_text = f"{token}\nQuestions to score:\n{questions_text}"
    return [
        {"role": "system", "content": [{"type": "text", "text": EVALUATION_SYSTEM}]},
        {"role": "user", "content": [{"type": "image"}, {"type": "text", "text": user_text}]},
    ]


class DynEvalRunner:
    """Loads the DynEval checkpoint and runs the full T2IA-to-evaluation pipeline."""

    def __init__(self, args: argparse.Namespace):
        """Load processor/model from a local checkpoint or the Hugging Face repo."""
        load_kwargs: dict[str, Any] = {
            "torch_dtype": getattr(torch, args.dtype) if args.dtype != "auto" else "auto",
            "device_map": args.device_map,
            "trust_remote_code": True,
        }
        processor_kwargs: dict[str, Any] = {"trust_remote_code": True}

        if args.checkpoint:
            model_ref = args.checkpoint
            subfolder = None
        else:
            model_ref = args.repo_id
            subfolder = HF_SUBFOLDERS[args.variant]

        if subfolder:
            load_kwargs["subfolder"] = subfolder
            processor_kwargs["subfolder"] = subfolder

        self.processor = AutoProcessor.from_pretrained(model_ref, **processor_kwargs)
        if self.processor.tokenizer.pad_token_id is None:
            self.processor.tokenizer.pad_token = self.processor.tokenizer.eos_token
        self.processor.tokenizer.padding_side = "left"

        self.model = Qwen3VLForConditionalGeneration.from_pretrained(model_ref, **load_kwargs).eval()
        self.t2ia_token = resolve_task_token(self.processor.tokenizer, "T2IA")
        self.evaluation_token = resolve_task_token(self.processor.tokenizer, "EVALUATION")

    @property
    def device(self):
        """Return the device where the loaded model currently lives."""
        return self.model.device

    def generate_text(self, messages: list[dict[str, Any]], max_new_tokens: int) -> str:
        """Run text-only generation for element extraction or question generation."""
        inputs = self.processor.apply_chat_template(
            messages,
            tokenize=True,
            add_generation_prompt=True,
            return_dict=True,
            return_tensors="pt",
        )
        inputs = {key: value.to(self.device) if torch.is_tensor(value) else value for key, value in inputs.items()}
        with torch.inference_mode():
            generated = self.model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False)
        input_width = inputs["input_ids"].shape[1]
        return self.processor.decode(generated[0, input_width:], skip_special_tokens=True, clean_up_tokenization_spaces=False)

    def generate_image(self, messages: list[dict[str, Any]], image: Image.Image, max_new_tokens: int) -> str:
        """Run image-conditioned generation for the evaluation/scoring step."""
        text = self.processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        inputs = self.processor(text=[text], images=[image], return_tensors="pt", padding=True)
        inputs = {key: value.to(self.device) if torch.is_tensor(value) else value for key, value in inputs.items()}
        with torch.inference_mode():
            generated = self.model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False)
        input_width = inputs["input_ids"].shape[1]
        return self.processor.decode(generated[0, input_width:], skip_special_tokens=True, clean_up_tokenization_spaces=False)

    def run(self, prompt: str, image_path: Path, args: argparse.Namespace) -> dict[str, Any]:
        """Execute elements -> questions -> image scoring for one prompt/image pair."""
        image = Image.open(image_path).convert("RGB")

        raw_elements = self.generate_text(build_element_messages(self.t2ia_token, prompt), args.max_new_tokens_elements)
        elements = parse_elements(raw_elements)

        questions = []
        raw_questions = []
        for element in elements:
            raw = self.generate_text(build_question_messages(self.t2ia_token, prompt, element), args.max_new_tokens_questions)
            raw_questions.append({"element": element, "raw": raw})
            question = parse_question(raw, element)
            if question:
                questions.append(question)
        questions = dedupe_questions(questions)

        raw_answers = self.generate_image(build_evaluation_messages(self.evaluation_token, questions), image, args.max_new_tokens_answers)
        answers = parse_answers(raw_answers, questions)

        result = {
            "prompt": prompt,
            "image_path": str(image_path),
            "elements": elements,
            "questions": questions,
            "answers": answers,
        }
        if args.hide_elements:
            result.pop("elements", None)
        if args.include_raw:
            result["raw_elements"] = raw_elements
            result["raw_questions"] = raw_questions
            result["raw_answers"] = raw_answers
        return result


def format_result(result: dict[str, Any]) -> str:
    """Format the pipeline result for readable terminal output."""
    lines = ["=" * 88, "DynEval Evaluator Result", "=" * 88]
    lines.append(f"Prompt: {result['prompt']}")
    lines.append(f"Image: {result['image_path']}")

    elements = result.get("elements", [])
    if isinstance(elements, list):
        lines.extend(["", f"Elements ({len(elements)})"])
        for idx, element in enumerate(elements, start=1):
            lines.append(f"  {idx}. {element}")

    questions = result.get("questions", [])
    lines.extend(["", f"Questions ({len(questions)})"])
    for idx, item in enumerate(questions, start=1):
        lines.append(f"  {idx}. {item.get('question', '')}")
        if item.get("answer"):
            lines.append(f"     ground-truth answer: {item['answer']}")

    answers = result.get("answers", [])
    lines.extend(["", f"Evaluation Scores ({len(answers)})"])
    valid_scores = []
    for idx, item in enumerate(answers, start=1):
        score = normalize_score(item.get("score"))
        if 1 <= score <= 5:
            valid_scores.append(score)
        lines.append(f"  {idx}. score={score} | {item.get('question', '')}")
        if item.get("reasoning"):
            lines.append(f"     reasoning: {item['reasoning']}")
    if valid_scores:
        lines.append(f"  Mean score: {sum(valid_scores) / len(valid_scores):.3f}")
    lines.append("=" * 88)
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    """Parse command-line options for local or Hugging Face inference."""
    parser = argparse.ArgumentParser(description="Run DynEval Evaluator inference from local or Hugging Face weights.")
    parser.add_argument("--checkpoint", type=str, default=None, help="Local checkpoint path. If set, this overrides --variant/--repo-id.")
    parser.add_argument("--repo-id", type=str, default=HF_REPO_ID, help="Hugging Face repo id used when --checkpoint is not set.")
    parser.add_argument("--variant", choices=["2b", "4b"], default="2b", help="HF model variant to load from the repo.")
    parser.add_argument("--prompt", type=str, required=True, help="Text-to-image prompt for the image.")
    parser.add_argument("--image", type=Path, required=True, help="Image path to evaluate.")
    parser.add_argument("--output-file", type=Path, default=None, help="Optional JSON output path.")
    parser.add_argument("--dtype", choices=["bfloat16", "float16", "float32", "auto"], default="bfloat16")
    parser.add_argument("--device-map", type=str, default="auto")
    parser.add_argument("--max-new-tokens-elements", type=int, default=256)
    parser.add_argument("--max-new-tokens-questions", type=int, default=256)
    parser.add_argument("--max-new-tokens-answers", type=int, default=768)
    parser.add_argument("--hide-elements", action="store_true", help="Hide intermediate elements from terminal and saved JSON.")
    parser.add_argument("--include-raw", action="store_true", help="Include raw model responses in saved JSON.")
    return parser.parse_args()


def main() -> None:
    """CLI entry point: validate inputs, run inference, print and optionally save JSON."""
    args = parse_args()
    if not args.image.exists():
        raise FileNotFoundError(f"Image not found: {args.image}")

    runner = DynEvalRunner(args)
    result = runner.run(args.prompt, args.image, args)

    print(format_result(result))
    if args.output_file:
        args.output_file.parent.mkdir(parents=True, exist_ok=True)
        args.output_file.write_text(json_dumps(result) + "\n", encoding="utf-8")
        print(f"\nSaved JSON: {args.output_file}")


if __name__ == "__main__":
    main()
