


from __future__ import annotations

import argparse
import json
import os
import random
from dataclasses import dataclass
from pathlib import Path

import torch
from torch.utils.data import Dataset
from PIL import Image


TASK_TOKENS = ["<T2IA>", "<IQA>", "<EVALUATION>"]
T2IA_TOKEN = "<T2IA>"
EVALUATION_TOKEN = "<EVALUATION>"

DEFAULT_MODEL = Path("checkpoints/base/QWEN3-VL-4B-INSTRUCT-MODEL")
DEFAULT_SOURCE_JSON = Path("/mnt/18_TB/shyam/dyneval_project/shyam_eccv/train_list_questions_avg5.json")
DEFAULT_IMAGE_ROOT = Path("/mnt/18_TB/shyam/dyneval_project/shyam_eccv/dataset/images")
DEFAULT_DATA_DIR = Path("data/sft/qwen3vl_t2ia_sft_data")
DEFAULT_QUESTION_DATA_DIR = Path("data/sft/qwen3vl_t2ia_question_sft_data")
DEFAULT_SINGLE_QUESTION_DATA_DIR = Path("data/sft/qwen3vl_t2ia_single_question_sft_data")
DEFAULT_MIXED_DATA_DIR = Path("data/sft/qwen3vl_t2ia_mixed_sft_data")
DEFAULT_EVALUATION_DATA_DIR = Path("data/sft/qwen3vl_evaluation_sft_data")
DEFAULT_OUTPUT_DIR = Path("qwen3vl-t2ia-lora")
DEFAULT_FULL_OUTPUT_DIR = Path("qwen3vl-t2ia-full")

T2IA_ELEMENT_SYSTEM = """Given an aigc prompt, extract the elements that are important for generating images.
Classify each element into a type (object, human, animal, food, activity, attribute, counting, color, material, spatial, location, shape, other).
Examples are as follows, where Elements is in json format.

Prompt: A man posing for a selfie in a jacket and bow tie.
Elements: ["man (human)", "selfie (activity)", "jacket (object)", "bow tie (object)", "posing (activity)"]

Prompt: A horse and several cows feed on hay.
Elements: ["horse (animal)", "cows (animal)", "hay (object)", "feed on (activity)", "several (counting)"]"""

T2IA_ELEMENT_USER_PROMPT = """<T2IA>
Prompt: {prompt}
Elements:"""

T2IA_QUESTION_SYSTEM = """Given an aigc prompt and its extracted text-to-image elements, generate one image-verification question for each element.
Each question must be answerable by inspecting a generated image.
The questions should evaluate whether the image satisfies the corresponding element.
Return only a JSON array of objects, where each object has exactly these keys: "element" and "question"."""

T2IA_QUESTION_USER_PROMPT = """<T2IA>
Prompt: {prompt}
Elements:
{elements_json}
Questions:"""

T2IA_SINGLE_QUESTION_SYSTEM = """Given a prompt for image generation and one of its related elements, generate one easy Yes/No question to verify whether the element is represented in the image generated by the prompt.
The question must be answerable by inspecting the image.
Return only JSON with exactly these keys: "question" and "answer".
The answer should be "yes" unless the element explicitly describes an absence or zero count."""

T2IA_SINGLE_QUESTION_USER_PROMPT = """<T2IA>
Description: {prompt}
Element: {element}
Return JSON:
{{"question": "...", "answer": "yes/no"}}"""

EVALUATION_SYSTEM = """You are a strict visual evidence evaluator. Your job is to test for image-text alignment by looking at the image and answering the questions respectively.
CRITICAL RULES:
1. Score based ONLY on what you can SEE in the image, not what the prompt says should be there.
2. Do NOT assume elements exist just because the prompt mentions them. Look at the actual pixels.
SCORING SCALE:
  5 = YES, DEFINITELY | 4 = YES, PROBABLY | 3 = UNCERTAIN | 2 = NO, PROBABLY | 1 = NO, DEFINITELY
EXAMPLE OUTPUT:
[{"question": "Is there a red car?", "score": 5}, {"question": "Are there two people?", "score": 2}]
Return ONLY a JSON array."""

EVALUATION_USER_PROMPT = """<EVALUATION>
Questions to score:
{questions_text}"""


def require_training_deps():
    try:
        from peft import LoraConfig, get_peft_model
        from transformers import AutoProcessor, Qwen3VLForConditionalGeneration, Trainer, TrainingArguments
    except Exception as exc:
        raise SystemExit(
            "Training dependencies are not importable. Install compatible versions, for example:\n"
            "  pip install 'huggingface-hub>=0.34,<1.0' 'transformers>=4.57.0' peft accelerate qwen-vl-utils\n"
            f"Import error: {exc}"
        )
    return AutoProcessor, Qwen3VLForConditionalGeneration, Trainer, TrainingArguments, LoraConfig, get_peft_model


def distributed_env() -> tuple[int, int]:
    return int(os.environ.get("WORLD_SIZE", "1")), int(os.environ.get("LOCAL_RANK", "-1"))


def json_dumps(value) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def build_t2ia_element_messages(prompt: str, elements: list[str]) -> list[dict]:
    return [
        {
            "role": "system",
            "content": [{"type": "text", "text": T2IA_ELEMENT_SYSTEM}],
        },
        {
            "role": "user",
            "content": [{"type": "text", "text": T2IA_ELEMENT_USER_PROMPT.format(prompt=prompt)}],
        },
        {"role": "assistant", "content": [{"type": "text", "text": json_dumps(elements)}]},
    ]


def build_t2ia_question_messages(prompt: str, elements: list[str], questions: list[dict]) -> list[dict]:
    return [
        {
            "role": "system",
            "content": [{"type": "text", "text": T2IA_QUESTION_SYSTEM}],
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": T2IA_QUESTION_USER_PROMPT.format(
                        prompt=prompt,
                        elements_json=json_dumps(elements),
                    ),
                }
            ],
        },
        {"role": "assistant", "content": [{"type": "text", "text": json_dumps(questions)}]},
    ]


def build_t2ia_single_question_messages(prompt: str, element: str, question: str) -> list[dict]:
    answer = "no" if element.strip().lower().startswith(("0 ", "zero ", "no ")) else "yes"
    target = {"question": question, "answer": answer}
    return [
        {
            "role": "system",
            "content": [{"type": "text", "text": T2IA_SINGLE_QUESTION_SYSTEM}],
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": T2IA_SINGLE_QUESTION_USER_PROMPT.format(prompt=prompt, element=element),
                }
            ],
        },
        {"role": "assistant", "content": [{"type": "text", "text": json_dumps(target)}]},
    ]


def rubric_score(raw_score) -> int:
    score = float(raw_score)
    if score <= 0.5:
        return 1
    return max(1, min(5, round((score / 5.0) * 4.0 + 1.0)))


def build_evaluation_messages(questions: list[str], answers: list[dict]) -> list[dict]:
    questions_text = "\n".join(f"{idx + 1}. Question: {question}" for idx, question in enumerate(questions))
    return [
        {
            "role": "system",
            "content": [{"type": "text", "text": EVALUATION_SYSTEM}],
        },
        {
            "role": "user",
            "content": [
                {"type": "image"},
                {"type": "text", "text": EVALUATION_USER_PROMPT.format(questions_text=questions_text)},
            ],
        },
        {"role": "assistant", "content": [{"type": "text", "text": json_dumps(answers)}]},
    ]


def resolve_image_path(image_ref: str, image_root: Path) -> Path | None:
    ref = Path(image_ref)
    candidates = [ref] if ref.is_absolute() else []
    candidates.extend([image_root / ref, image_root / ref.name])
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def split_and_write_rows(
    rows: list[dict],
    output_dir: Path,
    val_ratio: float,
    seed: int,
    manifest: dict,
) -> dict:
    if not rows:
        raise ValueError("No <T2IA> rows were built. Check the source JSON schema.")

    rng = random.Random(seed)
    rng.shuffle(rows)
    val_count = max(1, int(len(rows) * val_ratio)) if len(rows) > 1 else 0
    val_rows = rows[:val_count]
    train_rows = rows[val_count:]

    output_dir.mkdir(parents=True, exist_ok=True)
    for split, split_rows in [("train", train_rows), ("val", val_rows)]:
        with (output_dir / f"{split}.jsonl").open("w", encoding="utf-8") as handle:
            for row in split_rows:
                handle.write(json.dumps(row, ensure_ascii=False) + "\n")

    manifest.update(
        {
            "train_rows": len(train_rows),
            "val_rows": len(val_rows),
            "val_ratio": val_ratio,
            "seed": seed,
        }
    )
    (output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def build_element_rows(records: list[dict], limit: int | None = None) -> tuple[list[dict], int]:
    deduped: dict[tuple[str, str, tuple[str, ...]], dict] = {}
    skipped = 0
    for record in records:
        prompt_id = str(record.get("prompt_id", "")).strip()
        prompt = str(record.get("prompt", "")).strip()
        elements = record.get("elements")
        if not prompt_id or not prompt or not isinstance(elements, list) or not elements:
            skipped += 1
            continue
        normalized_elements = [str(element).strip() for element in elements if str(element).strip()]
        if not normalized_elements:
            skipped += 1
            continue
        key = (prompt_id, prompt, tuple(normalized_elements))
        deduped[key] = {
            "id": f"{prompt_id}_elements",
            "prompt_id": prompt_id,
            "prompt": prompt,
            "elements": normalized_elements,
            "messages": build_t2ia_element_messages(prompt, normalized_elements),
            "task": "T2IA_element_extraction",
        }
        if limit is not None and len(deduped) >= limit:
            break
    return list(deduped.values()), skipped


def build_question_rows(records: list[dict], limit: int | None = None) -> tuple[list[dict], int]:
    deduped: dict[tuple[str, str, tuple[str, ...], tuple[str, ...]], dict] = {}
    skipped = 0
    for record in records:
        prompt_id = str(record.get("prompt_id", "")).strip()
        prompt = str(record.get("prompt", "")).strip()
        elements = record.get("elements")
        element_score = record.get("element_score")
        if (
            not prompt_id
            or not prompt
            or not isinstance(elements, list)
            or not elements
            or not isinstance(element_score, dict)
            or not element_score
        ):
            skipped += 1
            continue

        normalized_elements = [str(element).strip() for element in elements if str(element).strip()]
        raw_questions = [str(question).strip() for question in element_score.keys() if str(question).strip()]
        if not normalized_elements or not raw_questions:
            skipped += 1
            continue

        questions = []
        for idx, question in enumerate(raw_questions):
            element = normalized_elements[idx] if idx < len(normalized_elements) else ""
            questions.append({"element": element, "question": question})

        key = (prompt_id, prompt, tuple(normalized_elements), tuple(raw_questions))
        deduped[key] = {
            "id": f"{prompt_id}_questions",
            "prompt_id": prompt_id,
            "prompt": prompt,
            "elements": normalized_elements,
            "questions": questions,
            "messages": build_t2ia_question_messages(prompt, normalized_elements, questions),
            "task": "T2IA_question_generation",
        }
        if limit is not None and len(deduped) >= limit:
            break
    return list(deduped.values()), skipped


def build_single_question_rows(records: list[dict], limit: int | None = None) -> tuple[list[dict], int]:
    deduped: dict[tuple[str, str, str, str], dict] = {}
    skipped = 0
    for record in records:
        prompt_id = str(record.get("prompt_id", "")).strip()
        prompt = str(record.get("prompt", "")).strip()
        elements = record.get("elements")
        element_score = record.get("element_score")
        if (
            not prompt_id
            or not prompt
            or not isinstance(elements, list)
            or not elements
            or not isinstance(element_score, dict)
            or not element_score
        ):
            skipped += 1
            continue

        normalized_elements = [str(element).strip() for element in elements if str(element).strip()]
        raw_questions = [str(question).strip() for question in element_score.keys() if str(question).strip()]
        if not normalized_elements or not raw_questions:
            skipped += 1
            continue

        for idx, question in enumerate(raw_questions):
            if idx >= len(normalized_elements):
                break
            element = normalized_elements[idx]
            key = (prompt_id, prompt, element, question)
            deduped[key] = {
                "id": f"{prompt_id}_single_question_{idx:03d}",
                "prompt_id": prompt_id,
                "prompt": prompt,
                "element": element,
                "question": question,
                "messages": build_t2ia_single_question_messages(prompt, element, question),
                "task": "T2IA_single_question_generation",
            }
            if limit is not None and len(deduped) >= limit:
                return list(deduped.values()), skipped
    return list(deduped.values()), skipped


def build_evaluation_rows(records: list[dict], image_root: Path, limit: int | None = None) -> tuple[list[dict], int]:
    rows: list[dict] = []
    skipped = 0
    for record in records:
        prompt_id = str(record.get("prompt_id", "")).strip()
        prompt = str(record.get("prompt", "")).strip()
        image_ref = str(record.get("img_path", "")).strip()
        element_score = record.get("element_score")
        if not prompt_id or not prompt or not image_ref or not isinstance(element_score, dict) or not element_score:
            skipped += 1
            continue

        image_path = resolve_image_path(image_ref, image_root)
        if image_path is None:
            skipped += 1
            continue

        questions: list[str] = []
        answers: list[dict] = []
        for question, raw_score in element_score.items():
            question_text = str(question).strip()
            if not question_text:
                continue
            try:
                score = rubric_score(raw_score)
            except (TypeError, ValueError):
                continue
            questions.append(question_text)
            answers.append({"question": question_text, "score": score})

        if not questions:
            skipped += 1
            continue

        rows.append(
            {
                "id": f"{prompt_id}_{Path(image_ref).parent.name}_evaluation",
                "prompt_id": prompt_id,
                "prompt": prompt,
                "image_ref": image_ref,
                "image_path": str(image_path),
                "questions": questions,
                "answers": answers,
                "messages": build_evaluation_messages(questions, answers),
                "task": "EVALUATION_scoring",
            }
        )
        if limit is not None and len(rows) >= limit:
            break
    return rows, skipped


def prepare_t2ia_sft(
    source_json: Path,
    output_dir: Path,
    val_ratio: float,
    seed: int,
    limit: int | None = None,
    t2ia_task: str = "element_extraction",
    image_root: Path = DEFAULT_IMAGE_ROOT,
) -> dict:
    records = json.loads(source_json.read_text(encoding="utf-8"))
    if not isinstance(records, list):
        raise ValueError(f"{source_json} must contain a JSON array")

    if t2ia_task == "element_extraction":
        rows, skipped = build_element_rows(records, limit)
    elif t2ia_task == "question_generation":
        rows, skipped = build_question_rows(records, limit)
    elif t2ia_task == "question_generation_single":
        rows, skipped = build_single_question_rows(records, limit)
    elif t2ia_task == "mixed":
        element_rows, element_skipped = build_element_rows(records, limit)
        question_limit = None if limit is None else max(0, limit - len(element_rows))
        question_rows, question_skipped = build_question_rows(records, question_limit)
        rows = element_rows + question_rows
        skipped = element_skipped + question_skipped
    elif t2ia_task == "mixed_with_single_questions":
        element_rows, element_skipped = build_element_rows(records, limit)
        question_rows, question_skipped = build_question_rows(records, None if limit is None else max(0, limit - len(element_rows)))
        single_question_rows, single_question_skipped = build_single_question_rows(records, None)
        rows = element_rows + question_rows + single_question_rows
        if limit is not None:
            rows = rows[:limit]
        skipped = element_skipped + question_skipped + single_question_skipped
    elif t2ia_task == "evaluation":
        rows, skipped = build_evaluation_rows(records, image_root, limit)
    else:
        raise ValueError(f"Unsupported --t2ia-task: {t2ia_task}")

    manifest = {
        "task": t2ia_task,
        "source_json": str(source_json),
        "image_root": str(image_root) if t2ia_task == "evaluation" else None,
        "registered_task_tokens": TASK_TOKENS,
        "raw_rows": len(records),
        "deduped_rows": len(rows),
        "skipped_rows": skipped,
    }
    return split_and_write_rows(rows, output_dir, val_ratio, seed, manifest)


class JsonlConversationDataset(Dataset):
    def __init__(self, path: Path, max_samples: int | None = None):
        self.rows = []
        with path.open("r", encoding="utf-8") as handle:
            for line in handle:
                if line.strip():
                    self.rows.append(json.loads(line))
                if max_samples is not None and len(self.rows) >= max_samples:
                    break

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, idx: int) -> dict:
        return self.rows[idx]


def tensor_without_batch_dim(key: str, value):
    if key in {"input_ids", "attention_mask", "assistant_masks", "mm_token_type_ids"}:
        return value.squeeze(0)
    return value


def mask_assistant_spans(input_ids: torch.Tensor, messages: list[dict], tokenizer) -> torch.Tensor:
    labels_mask = torch.zeros_like(input_ids, dtype=torch.bool)
    cursor = 0
    for message in messages:
        if message.get("role") != "assistant":
            continue
        content = message.get("content", "")
        if isinstance(content, list):
            content = "".join(part.get("text", "") for part in content if isinstance(part, dict) and part.get("type") == "text")
        if not isinstance(content, str) or not content:
            continue
        answer_ids = tokenizer(content, add_special_tokens=False, return_tensors="pt")["input_ids"].squeeze(0)
        if answer_ids.numel() == 0 or answer_ids.numel() > input_ids.numel():
            continue
        for start in range(cursor, input_ids.numel() - answer_ids.numel() + 1):
            if torch.equal(input_ids[start : start + answer_ids.numel()].cpu(), answer_ids.cpu()):
                labels_mask[start : start + answer_ids.numel()] = True
                cursor = start + answer_ids.numel()
                break
    return labels_mask


@dataclass
class TextConversationCollator:
    processor: object
    max_length: int
    train_all_tokens_if_no_mask: bool = False

    def __call__(self, features: list[dict]) -> dict[str, torch.Tensor]:
        batch_inputs = []
        for row in features:
            if row.get("image_path"):
                text = self.processor.apply_chat_template(
                    row["messages"],
                    tokenize=False,
                    add_generation_prompt=False,
                )
                image = Image.open(row["image_path"]).convert("RGB")
                encoded = self.processor(
                    text=[text],
                    images=[image],
                    return_tensors="pt",
                    padding=False,
                    truncation=True,
                    max_length=self.max_length,
                )
            else:
                encoded = self.processor.apply_chat_template(
                    row["messages"],
                    tokenize=True,
                    add_generation_prompt=False,
                    return_dict=True,
                    return_tensors="pt",
                    return_assistant_tokens_mask=True,
                    processor_kwargs={
                        "padding": False,
                        "truncation": True,
                        "max_length": self.max_length,
                    },
                )
            item = {key: tensor_without_batch_dim(key, value) for key, value in encoded.items() if torch.is_tensor(value)}
            item["_manual_assistant_mask"] = mask_assistant_spans(item["input_ids"], row["messages"], self.processor.tokenizer)
            batch_inputs.append(item)

        tokenizer = self.processor.tokenizer
        input_ids = torch.nn.utils.rnn.pad_sequence(
            [item["input_ids"] for item in batch_inputs],
            batch_first=True,
            padding_value=tokenizer.pad_token_id,
        )
        attention_mask = torch.nn.utils.rnn.pad_sequence(
            [item["attention_mask"] for item in batch_inputs],
            batch_first=True,
            padding_value=0,
        )
        labels = input_ids.clone()

        if "assistant_masks" in batch_inputs[0] and any(item["assistant_masks"].sum().item() > 0 for item in batch_inputs):
            assistant_mask = torch.nn.utils.rnn.pad_sequence(
                [item["assistant_masks"] for item in batch_inputs],
                batch_first=True,
                padding_value=0,
            )
            labels[assistant_mask == 0] = -100
        elif any(item["_manual_assistant_mask"].sum().item() > 0 for item in batch_inputs):
            assistant_mask = torch.nn.utils.rnn.pad_sequence(
                [item["_manual_assistant_mask"] for item in batch_inputs],
                batch_first=True,
                padding_value=0,
            )
            labels[assistant_mask == 0] = -100
        elif not self.train_all_tokens_if_no_mask:
            raise RuntimeError("Could not identify assistant tokens. Use --train-all-tokens-if-no-mask to continue.")

        labels[attention_mask == 0] = -100
        output = {"input_ids": input_ids, "attention_mask": attention_mask, "labels": labels}
        if all("mm_token_type_ids" in item for item in batch_inputs):
            output["mm_token_type_ids"] = torch.nn.utils.rnn.pad_sequence(
                [item["mm_token_type_ids"] for item in batch_inputs],
                batch_first=True,
                padding_value=0,
            )
        vision_tensor_keys = {"pixel_values", "image_grid_thw", "pixel_values_videos", "video_grid_thw"}
        extra_tensor_keys = sorted(
            key
            for item in batch_inputs
            for key in item
            if key in vision_tensor_keys and torch.is_tensor(item[key])
        )
        for key in extra_tensor_keys:
            values = [item[key] for item in batch_inputs if key in item]
            if len(values) == len(batch_inputs):
                output[key] = torch.cat(values, dim=0) if values[0].dim() > 0 else torch.stack(values)
        return output


def register_task_tokens(processor, model) -> int:
    tokenizer = processor.tokenizer
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token
    existing_special_tokens = list(getattr(tokenizer, "additional_special_tokens", []) or [])
    merged_special_tokens = existing_special_tokens + [
        token for token in TASK_TOKENS if token not in existing_special_tokens
    ]
    old_vocab_size = len(tokenizer)
    tokenizer.add_special_tokens({"additional_special_tokens": merged_special_tokens})
    added = len(tokenizer) - old_vocab_size
    if added:
        model.resize_token_embeddings(len(tokenizer))
    return added


def count_trainable_parameters(model) -> tuple[int, int]:
    trainable = sum(param.numel() for param in model.parameters() if param.requires_grad)
    total = sum(param.numel() for param in model.parameters())
    return trainable, total


def train_t2ia(args: argparse.Namespace) -> None:
    AutoProcessor, Qwen3VLForConditionalGeneration, Trainer, TrainingArguments, LoraConfig, get_peft_model = (
        require_training_deps()
    )

    world_size, local_rank = distributed_env()
    is_distributed = world_size > 1
    device_map = args.device_map or "none"
    if is_distributed and device_map != "none":
        raise ValueError("Use --device-map none for torchrun/accelerate multi-GPU DDP training.")
    if torch.cuda.is_available() and local_rank >= 0:
        torch.cuda.set_device(local_rank)

    processor = AutoProcessor.from_pretrained(args.model_path, trust_remote_code=True)
    model_kwargs = {"torch_dtype": torch.bfloat16, "trust_remote_code": True}
    if device_map == "auto":
        model_kwargs["device_map"] = "auto"
    model = Qwen3VLForConditionalGeneration.from_pretrained(args.model_path, **model_kwargs)

    added = register_task_tokens(processor, model)
    print(f"Registered task tokens: {TASK_TOKENS}; newly added={added}; vocab_size={len(processor.tokenizer)}")

    if args.gradient_checkpointing:
        model.gradient_checkpointing_enable()
        model.config.use_cache = False

    if args.finetune_mode == "lora":
        lora_config = LoraConfig(
            r=args.lora_r,
            lora_alpha=args.lora_alpha,
            lora_dropout=args.lora_dropout,
            bias="none",
            task_type="CAUSAL_LM",
            target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
            modules_to_save=["embed_tokens", "lm_head"],
        )
        model = get_peft_model(model, lora_config)
        model.print_trainable_parameters()
    else:
        for param in model.parameters():
            param.requires_grad_(True)
        trainable, total = count_trainable_parameters(model)
        print(
            f"Full fine-tuning enabled: trainable params={trainable:,} || "
            f"all params={total:,} || trainable%={100 * trainable / total:.4f}"
        )

    train_ds = JsonlConversationDataset(args.train_file, args.max_train_samples)
    eval_ds = JsonlConversationDataset(args.val_file, args.max_val_samples) if args.val_file.exists() else None
    collator = TextConversationCollator(
        processor=processor,
        max_length=args.max_length,
        train_all_tokens_if_no_mask=args.train_all_tokens_if_no_mask,
    )

    training_args = TrainingArguments(
        output_dir=str(args.output_dir),
        num_train_epochs=args.epochs,
        learning_rate=args.lr,
        lr_scheduler_type=args.lr_scheduler_type,
        warmup_ratio=args.warmup_ratio,
        warmup_steps=args.warmup_steps,
        per_device_train_batch_size=args.per_device_train_batch_size,
        per_device_eval_batch_size=args.per_device_eval_batch_size,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        bf16=True,
        logging_steps=args.logging_steps,
        save_steps=args.save_steps,
        eval_steps=args.eval_steps,
        eval_strategy="steps" if eval_ds else "no",
        save_strategy="steps",
        optim=args.optim,
        remove_unused_columns=False,
        report_to=args.report_to,
        dataloader_num_workers=args.dataloader_num_workers,
        ddp_find_unused_parameters=args.ddp_find_unused_parameters if is_distributed else None,
    )
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=eval_ds,
        data_collator=collator,
    )
    trainer.train()
    trainer.save_model(args.output_dir)
    processor.save_pretrained(args.output_dir)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Prepare and fine-tune Qwen3-VL-4B for DynEVAL task tokens.")
    parser.add_argument("--prepare-only", action="store_true")
    parser.add_argument("--train-only", action="store_true")
    parser.add_argument("--source-json", type=Path, default=DEFAULT_SOURCE_JSON)
    parser.add_argument("--image-root", type=Path, default=DEFAULT_IMAGE_ROOT)
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR)
    parser.add_argument(
        "--t2ia-task",
        choices=[
            "element_extraction",
            "question_generation",
            "question_generation_single",
            "mixed",
            "mixed_with_single_questions",
            "evaluation",
        ],
        default="element_extraction",
        help="Which SFT dataset to prepare. Training reads whichever JSONL files --data-dir points to.",
    )
    parser.add_argument("--val-ratio", type=float, default=0.02)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--model-path", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--train-file", type=Path, default=None)
    parser.add_argument("--val-file", type=Path, default=None)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--finetune-mode",
        choices=["lora", "full"],
        default="lora",
        help="Use 'lora' for adapter training or 'full' to update and save all model weights.",
    )
    parser.add_argument("--max-length", type=int, default=2048)
    parser.add_argument("--max-train-samples", type=int, default=None)
    parser.add_argument("--max-val-samples", type=int, default=512)
    parser.add_argument("--epochs", type=float, default=1.0)
    parser.add_argument("--lr", type=float, default=2e-5)
    parser.add_argument(
        "--lr-scheduler-type",
        type=str,
        default="linear",
        help="Learning-rate scheduler type passed to Trainer, e.g. linear or cosine.",
    )
    parser.add_argument("--warmup-ratio", type=float, default=0.0)
    parser.add_argument("--warmup-steps", type=int, default=0)
    parser.add_argument(
        "--optim",
        type=str,
        default="adamw_torch",
        help="Trainer optimizer. For full fine-tuning on limited VRAM, try 'adafactor'.",
    )
    parser.add_argument("--per-device-train-batch-size", type=int, default=1)
    parser.add_argument("--per-device-eval-batch-size", type=int, default=1)
    parser.add_argument("--gradient-accumulation-steps", type=int, default=8)
    parser.add_argument("--logging-steps", type=int, default=10)
    parser.add_argument(
        "--report-to",
        type=str,
        default="none",
        help="Trainer reporting backend. Use 'wandb' to log to Weights & Biases.",
    )
    parser.add_argument("--save-steps", type=int, default=500)
    parser.add_argument("--eval-steps", type=int, default=500)
    parser.add_argument("--lora-r", type=int, default=16)
    parser.add_argument("--lora-alpha", type=int, default=32)
    parser.add_argument("--lora-dropout", type=float, default=0.05)
    parser.add_argument("--gradient-checkpointing", action="store_true")
    parser.add_argument(
        "--ddp-find-unused-parameters",
        action="store_true",
        help=(
            "Enable DDP unused-parameter detection. Use this for mixed text-only/image "
            "replay training where some batches do not touch the vision tower."
        ),
    )
    parser.add_argument("--train-all-tokens-if-no-mask", action="store_true")
    parser.add_argument(
        "--device-map",
        choices=["auto", "none"],
        default=None,
        help=(
            "Use 'none' for training. 'auto' may offload modules before token embeddings "
            "are resized and can fail after registering task tokens."
        ),
    )
    parser.add_argument("--dataloader-num-workers", type=int, default=2)
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    if args.prepare_only and args.train_only:
        raise SystemExit("Use only one of --prepare-only or --train-only.")

    train_file_was_default = args.train_file is None
    val_file_was_default = args.val_file is None
    if args.data_dir == DEFAULT_DATA_DIR:
        if args.t2ia_task == "question_generation":
            args.data_dir = DEFAULT_QUESTION_DATA_DIR
        elif args.t2ia_task == "question_generation_single":
            args.data_dir = DEFAULT_SINGLE_QUESTION_DATA_DIR
        elif args.t2ia_task == "mixed":
            args.data_dir = DEFAULT_MIXED_DATA_DIR
        elif args.t2ia_task == "mixed_with_single_questions":
            args.data_dir = Path("data/sft/qwen3vl_t2ia_mixed_single_sft_data")
        elif args.t2ia_task == "evaluation":
            args.data_dir = DEFAULT_EVALUATION_DATA_DIR
    if train_file_was_default:
        args.train_file = args.data_dir / "train.jsonl"
    if val_file_was_default:
        args.val_file = args.data_dir / "val.jsonl"
    if args.finetune_mode == "full" and args.output_dir == DEFAULT_OUTPUT_DIR:
        args.output_dir = DEFAULT_FULL_OUTPUT_DIR

    if not args.train_only:
        manifest = prepare_t2ia_sft(
            source_json=args.source_json,
            output_dir=args.data_dir,
            val_ratio=args.val_ratio,
            seed=args.seed,
            limit=args.limit,
            t2ia_task=args.t2ia_task,
            image_root=args.image_root,
        )
        print(json.dumps(manifest, indent=2))

    if args.prepare_only:
        return

    if not args.train_file.exists():
        raise SystemExit(f"Missing train file: {args.train_file}. Run without --train-only first.")

    train_t2ia(args)


if __name__ == "__main__":
    main()
