

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path
from typing import Any


T2IA_ELEMENT_SYSTEM = """Given an aigc prompt, extract the elements that are important for generating images.
Classify each element into a type (object, human, animal, food, activity, attribute, counting, color, material, spatial, location, shape, other)."""

T2IA_SINGLE_QUESTION_SYSTEM = """Given a prompt for image generation and one of its related elements, generate one easy Yes/No question to verify whether the element is represented in the image generated by the prompt.
The question must be answerable by inspecting the image.
Return only JSON with exactly these keys: "question" and "answer"."""

EVALUATION_SYSTEM = """You are a strict visual evidence evaluator. Score based ONLY on what you can SEE in the image, not what the prompt says should be there.
Use this scale: 5 = yes definitely, 4 = yes probably, 3 = uncertain, 2 = no probably, 1 = no definitely.
Return ONLY a JSON array."""


def text_content(text: str) -> list[dict[str, str]]:
    return [{"type": "text", "text": text}]


def json_dumps(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_jsonl(rows: list[dict[str, Any]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def resolve_image_path(image_ref: str, images_root: Path) -> Path | None:
    ref = Path(image_ref)
    candidates = [ref] if ref.is_absolute() else []
    candidates.extend([images_root / ref, images_root / ref.name])
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def clean_questions(items: Any) -> list[dict[str, str]]:
    out = []
    seen = set()
    if not isinstance(items, list):
        return out
    for item in items:
        if not isinstance(item, dict):
            continue
        element = str(item.get("element", "")).strip()
        question = str(item.get("question", "")).strip()
        answer = str(item.get("answer", "yes")).strip().lower()
        if not element or not question:
            continue
        key = (element.lower(), question.lower())
        if key in seen:
            continue
        seen.add(key)
        out.append({"element": element, "question": question, "answer": "no" if answer.startswith("no") else "yes"})
    return out


def build_t2ia_rows(questions_dir: Path) -> list[dict[str, Any]]:
    rows = []
    for path in sorted(questions_dir.glob("*.json")):
        data = read_json(path)
        if not isinstance(data, dict):
            continue
        prompt_id = str(data.get("text_id") or data.get("prompt_id") or path.stem).strip()
        prompt = str(data.get("prompt") or data.get("text") or "").strip()
        questions = clean_questions(data.get("questions", []))
        if not prompt_id or not prompt or not questions:
            continue

        elements = []
        seen_elements = set()
        for item in questions:
            key = item["element"].lower()
            if key not in seen_elements:
                seen_elements.add(key)
                elements.append(item["element"])

        rows.append(
            {
                "id": f"{prompt_id}_elements",
                "prompt_id": prompt_id,
                "prompt": prompt,
                "elements": elements,
                "task": "T2IA_element_extraction",
                "messages": [
                    {"role": "system", "content": text_content(T2IA_ELEMENT_SYSTEM)},
                    {"role": "user", "content": text_content(f"<T2IA>\nPrompt: {prompt}\nElements:")},
                    {"role": "assistant", "content": text_content(json_dumps(elements))},
                ],
            }
        )

        for idx, item in enumerate(questions):
            target = {"question": item["question"], "answer": item["answer"]}
            rows.append(
                {
                    "id": f"{prompt_id}_single_question_{idx:03d}",
                    "prompt_id": prompt_id,
                    "prompt": prompt,
                    "element": item["element"],
                    "question": item["question"],
                    "task": "T2IA_single_question_generation",
                    "messages": [
                        {"role": "system", "content": text_content(T2IA_SINGLE_QUESTION_SYSTEM)},
                        {
                            "role": "user",
                            "content": text_content(
                                f'<T2IA>\nDescription: {prompt}\nElement: {item["element"]}\nReturn JSON:\n{{"question": "...", "answer": "yes/no"}}'
                            ),
                        },
                        {"role": "assistant", "content": text_content(json_dumps(target))},
                    ],
                }
            )
    return rows


def build_evaluation_rows(answers_dir: Path, images_root: Path) -> tuple[list[dict[str, Any]], int]:
    rows = []
    skipped = 0
    for path in sorted(answers_dir.glob("*.json")):
        data = read_json(path)
        records = data.get("results") if isinstance(data, dict) and isinstance(data.get("results"), list) else [data]
        for idx, record in enumerate(records):
            if not isinstance(record, dict):
                skipped += 1
                continue
            prompt_id = str(record.get("text_id") or record.get("prompt_id") or record.get("item_id") or path.stem).strip()
            prompt = str(record.get("prompt") or record.get("text") or "").strip()
            image_ref = str(record.get("image_ref") or record.get("image_path") or "").strip()
            answers = record.get("answers", [])
            if not prompt_id or not prompt or not image_ref or not isinstance(answers, list):
                skipped += 1
                continue
            image_path = resolve_image_path(image_ref, images_root)
            if image_path is None:
                skipped += 1
                continue

            questions = []
            clean_answers = []
            for item in answers:
                if not isinstance(item, dict):
                    continue
                question = str(item.get("question", "")).strip()
                if not question:
                    continue
                try:
                    score = int(round(float(item.get("score"))))
                except (TypeError, ValueError):
                    continue
                if not 1 <= score <= 5:
                    continue
                questions.append(question)
                clean_answers.append({"question": question, "score": score})
            if not clean_answers:
                skipped += 1
                continue

            q_text = "\n".join(f"{i + 1}. Question: {question}" for i, question in enumerate(questions))
            rows.append(
                {
                    "id": f"{prompt_id}_evaluation_{idx:03d}",
                    "prompt_id": prompt_id,
                    "prompt": prompt,
                    "image_ref": image_ref,
                    "image_path": str(image_path),
                    "questions": questions,
                    "answers": clean_answers,
                    "task": "EVALUATION_scoring",
                    "messages": [
                        {"role": "system", "content": text_content(EVALUATION_SYSTEM)},
                        {
                            "role": "user",
                            "content": [
                                {"type": "image"},
                                {"type": "text", "text": f"<EVALUATION>\nQuestions to score:\n{q_text}"},
                            ],
                        },
                        {"role": "assistant", "content": text_content(json_dumps(clean_answers))},
                    ],
                }
            )
    return rows, skipped


def split_rows(rows: list[dict[str, Any]], val_ratio: float, seed: int) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    rng = random.Random(seed)
    rng.shuffle(rows)
    val_count = max(1, int(len(rows) * val_ratio)) if len(rows) > 1 else 0
    return rows[val_count:], rows[:val_count]


def main() -> None:
    parser = argparse.ArgumentParser(description="Build DynEval SFT JSONL from question/answer folders.")
    parser.add_argument("--questions-dir", type=Path, required=True)
    parser.add_argument("--answers-dir", type=Path, required=True)
    parser.add_argument("--images-root", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--val-ratio", type=float, default=0.05)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    rows = []
    rows.extend(build_t2ia_rows(args.questions_dir))
    eval_rows, skipped_eval = build_evaluation_rows(args.answers_dir, args.images_root)
    rows.extend(eval_rows)
    if not rows:
        raise SystemExit("No rows were built. Check input folder schemas and image paths.")

    train_rows, val_rows = split_rows(rows, args.val_ratio, args.seed)
    write_jsonl(train_rows, args.output_dir / "train.jsonl")
    write_jsonl(val_rows, args.output_dir / "val.jsonl")

    manifest = {
        "questions_dir": str(args.questions_dir),
        "answers_dir": str(args.answers_dir),
        "images_root": str(args.images_root),
        "output_dir": str(args.output_dir),
        "train_rows": len(train_rows),
        "val_rows": len(val_rows),
        "total_rows": len(rows),
        "skipped_evaluation_rows": skipped_eval,
        "val_ratio": args.val_ratio,
        "seed": args.seed,
    }
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
