import argparse
import json
import re
from pathlib import Path

from transformers import AutoProcessor, Qwen3VLMoeForConditionalGeneration

BASE_DIR = Path(__file__).resolve().parent
ANNOTATIONS_FILE = Path("DYNEVAL-250K-PROMPTS.json")
IMAGES_ROOT = None
QUESTIONS_DIR = Path("t2ia_questions")
ANSWERS_DIR = Path("t2ia_answers")
DEFAULT_MODEL = "Qwen/Qwen3-VL-235B-A22B-Instruct"
FP8_MODEL = "Qwen/Qwen3-VL-235B-A22B-Instruct-FP8"

# Prompts mirror inference/run-inference.py so the teacher produces annotations in
# the exact style the student learns. The <T2IA>/<EVALUATION> task tokens are
# intentionally NOT sent to the teacher VLM (the SFT builders add them later).
ELEMENT_SYSTEM = """Given an aigc prompt, extract the elements that are important for generating images.
Classify each element into a type (object, human, animal, food, activity, attribute, counting, color, material, spatial, location, shape, other).
Do NOT extract medium or framing words that only describe how the image is captured or rendered, such as "photo", "photograph", "image", "picture", "shot", "render", "3D render", "illustration", "drawing", or "wallpaper". Ignore leading phrases like "a photo of", "a picture of", or "an image of" and only extract the actual visual content that follows.
Examples are as follows, where Elements is in json format.

Prompt: A man posing for a selfie in a jacket and bow tie.
Elements: ["man (human)", "selfie (activity)", "jacket (object)", "bow tie (object)", "posing (activity)"]

Prompt: A horse and several cows feed on hay.
Elements: ["horse (animal)", "cows (animal)", "hay (object)", "feed on (activity)", "several (counting)"]

Prompt: A photo of a bench.
Elements: ["bench (object)"]

Prompt: An illustration of a red apple on a table.
Elements: ["apple (object)", "red (color)", "table (object)", "on (spatial)"]"""

SINGLE_QUESTION_SYSTEM = """Given a prompt for image generation and one of its related elements, generate one easy Yes/No question to verify whether the element is represented in the image generated by the prompt.
The question must be answerable by inspecting the image.
Return only JSON with exactly these keys: "question" and "answer".
The answer should be "yes" unless the element explicitly describes an absence or zero count."""

EVALUATION_SYSTEM = """You are a strict visual evidence evaluator. Your job is to test for image-text alignment by looking at the image and answering the questions respectively.
CRITICAL RULES:
1. Score based ONLY on what you can SEE in the image, not what the prompt says should be there.
2. Do NOT assume elements exist just because the prompt mentions them. Look at the actual pixels.
SCORING SCALE:
  5 = YES, DEFINITELY | 4 = YES, PROBABLY | 3 = UNCERTAIN | 2 = NO, PROBABLY | 1 = NO, DEFINITELY
Return ONLY a JSON array."""

MEDIUM_ELEMENT_WORDS = {
    "photo", "photograph", "photography", "image", "picture", "pic", "shot",
    "snapshot", "render", "rendering", "3d render", "illustration", "drawing",
    "sketch", "painting", "artwork", "wallpaper", "poster", "portrait",
}


def resolve_input_path(path: Path) -> Path:
    if path.exists():
        return path
    script_relative = BASE_DIR / path
    if script_relative.exists():
        return script_relative
    repo_relative = BASE_DIR.parents[1] / path
    if repo_relative.exists():
        return repo_relative
    return path


def load_json(path: Path):
    with resolve_input_path(path).open("r", encoding="utf-8") as f:
        return json.load(f)


def load_annotations(annotations_file: Path) -> list[dict]:
    data = load_json(annotations_file)

    if isinstance(data, dict) and isinstance(data.get("prompts"), list):
        records: list[dict] = []
        for item in data["prompts"]:
            if not isinstance(item, dict):
                continue
            pair_id = str(item.get("pair_id", "")).strip()
            prompt = str(item.get("prompt", "")).strip()
            image_path = str(item.get("image_path", "")).strip()
            if not pair_id or not prompt or not image_path:
                continue
            records.append(
                {
                    "item_key": pair_id,
                    "pair_id": pair_id,
                    "text_id": str(item.get("text_id", pair_id)).strip() or pair_id,
                    "prompt": prompt,
                    "model": str(item.get("generation_model", "unknown")).strip() or "unknown",
                    "image_id": pair_id,
                    "image_path": image_path,
                    "questions_file": str(item.get("questions_file", "")).strip(),
                    "response_file": str(item.get("response_file", "")).strip(),
                    "group_id": str(item.get("group_id", "")).strip(),
                    "source_item_id": str(item.get("source_item_id", "")).strip(),
                }
            )
        if records:
            return records
        raise ValueError("No valid prompt/image records found in prompt mapping JSON")

    raise ValueError("annotations file must be a prompt mapping JSON object with a prompts list")


def parse_response_json(raw: str):
    text = (raw or "").strip()
    if text == "":
        return None

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    decoder = json.JSONDecoder()
    for opener in ("[", "{"):
        start = text.find(opener)
        while start >= 0:
            try:
                data, _ = decoder.raw_decode(text[start:])
                if isinstance(data, (list, dict)):
                    return data
            except json.JSONDecodeError:
                pass
            start = text.find(opener, start + 1)

    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        try:
            return json.loads("\n".join(lines).strip())
        except json.JSONDecodeError:
            return None

    return None


def normalize_confidence_score(value) -> int:
    """Normalize a value to a 1-5 score. Returns 0 if invalid."""
    try:
        score = int(round(float(value)))
    except (TypeError, ValueError):
        s = str(value).strip().lower()
        if s.startswith("yes") or re.search(r"\byes\b", s):
            return 5
        if s.startswith("no") or re.search(r"\bno\b", s):
            return 1
        match = re.search(r"\b([1-5])\b", s)
        return int(match.group(1)) if match else 0
    return score if 1 <= score <= 5 else 0


def parse_elements(raw) -> list[str]:
    """Parse the element-extraction response into a clean, de-duplicated list."""
    if isinstance(raw, str):
        raw = parse_response_json(raw)

    items: list[str] = []
    if isinstance(raw, list):
        items = [str(item).strip() for item in raw if str(item).strip()]
    elif isinstance(raw, dict):
        for key in ("elements", "Elements"):
            if isinstance(raw.get(key), list):
                items = [str(item).strip() for item in raw[key] if str(item).strip()]
                break

    out: list[str] = []
    seen: set[str] = set()
    for item in items:
        base = re.sub(r"\(.*?\)", "", item).strip(" .'\"").lower()
        if base in MEDIUM_ELEMENT_WORDS:
            continue
        key = re.sub(r"\s+", " ", item.lower())
        if key and key not in seen:
            seen.add(key)
            out.append(item)
    return out


def parse_single_question(raw, element: str) -> dict[str, str] | None:
    """Parse one generated yes/no question for a specific element."""
    data = parse_response_json(raw)
    if isinstance(data, list) and data:
        data = data[0]
    if not isinstance(data, dict):
        return None
    question = str(data.get("question", "")).strip()
    answer = str(data.get("answer", "yes")).strip().lower()
    if not question:
        return None
    return {"element": element, "question": question, "answer": "no" if answer.startswith("no") else "yes"}


def use_vllm_backend(model_name: str, backend: str) -> bool:
    if backend == "vllm":
        return True
    if backend == "transformers":
        return False
    return model_name == FP8_MODEL or model_name.endswith("-FP8")


def prepare_inputs_for_vllm(messages, processor):
    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    has_vision = any(
        isinstance(content, dict) and content.get("type") in {"image", "video"}
        for message in messages
        for content in message.get("content", [])
    )
    if not has_vision:
        return {"prompt": text}

    from qwen_vl_utils import process_vision_info

    image_inputs, video_inputs, video_kwargs = process_vision_info(
        messages,
        image_patch_size=processor.image_processor.patch_size,
        return_video_kwargs=True,
        return_video_metadata=True,
    )

    mm_data = {}
    if image_inputs is not None:
        mm_data["image"] = image_inputs
    if video_inputs is not None:
        mm_data["video"] = video_inputs

    inputs = {"prompt": text}
    if mm_data:
        inputs["multi_modal_data"] = mm_data
    if video_kwargs:
        inputs["mm_processor_kwargs"] = video_kwargs
    return inputs


class QwenGenerator:
    def __init__(
        self,
        model_name: str,
        backend: str,
        gpu_memory_utilization: float,
        tensor_parallel_size: int | None,
        temperature: float,
    ):
        self.model_name = model_name
        self.backend = "vllm" if use_vllm_backend(model_name, backend) else "transformers"
        self.temperature = temperature
        self.processor = AutoProcessor.from_pretrained(model_name)

        if self.backend == "vllm":
            import os

            os.environ["VLLM_WORKER_MULTIPROC_METHOD"] = "spawn"

            import torch
            from vllm import LLM

            tp_size = tensor_parallel_size or torch.cuda.device_count() or 1
            self.model = LLM(
                model=model_name,
                trust_remote_code=True,
                gpu_memory_utilization=gpu_memory_utilization,
                enforce_eager=False,
                tensor_parallel_size=tp_size,
                seed=0,
            )
        else:
            self.model = Qwen3VLMoeForConditionalGeneration.from_pretrained(
                model_name,
                dtype="auto",
                device_map="auto",
            )

    def generate(self, messages: list[dict], max_new_tokens: int) -> str:
        if self.backend == "vllm":
            from vllm import SamplingParams

            sampling_params = SamplingParams(
                temperature=self.temperature,
                max_tokens=max_new_tokens,
                top_k=-1,
                stop_token_ids=[],
            )
            outputs = self.model.generate(
                [prepare_inputs_for_vllm(messages, self.processor)],
                sampling_params=sampling_params,
            )
            return outputs[0].outputs[0].text.strip() if outputs else ""

        inputs = self.processor.apply_chat_template(
            messages,
            tokenize=True,
            add_generation_prompt=True,
            return_dict=True,
            return_tensors="pt",
        )
        inputs = inputs.to(self.model.device)

        generated_ids = self.model.generate(**inputs, max_new_tokens=max_new_tokens)
        generated_ids_trimmed = [
            out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
        ]
        output_text = self.processor.batch_decode(
            generated_ids_trimmed,
            skip_special_tokens=True,
            clean_up_tokenization_spaces=False,
        )
        return output_text[0].strip() if output_text else ""


def build_element_messages(prompt: str) -> list[dict]:
    return [
        {"role": "system", "content": [{"type": "text", "text": ELEMENT_SYSTEM}]},
        {"role": "user", "content": [{"type": "text", "text": f"Prompt: {prompt}\nElements:"}]},
    ]


def build_question_messages(prompt: str, element: str) -> list[dict]:
    user_text = (
        f"Description: {prompt}\nElement: {element}\n"
        'Return JSON:\n{"question": "...", "answer": "yes/no"}'
    )
    return [
        {"role": "system", "content": [{"type": "text", "text": SINGLE_QUESTION_SYSTEM}]},
        {"role": "user", "content": [{"type": "text", "text": user_text}]},
    ]


def build_evaluation_messages(image_path: Path, questions: list[dict[str, str]]) -> list[dict]:
    questions_text = "\n".join(f"{i}. Question: {q['question']}" for i, q in enumerate(questions, start=1))
    user_text = (
        f"Questions to score:\n{questions_text}\n\n"
        "Return ONLY a JSON array, one object per question in the same order:\n"
        '[{"question": "...", "score": 5, "reasoning": "..."}]\n'
        'Each "score" must be an integer from 1 to 5 using the scoring scale above.'
    )
    return [
        {"role": "system", "content": [{"type": "text", "text": EVALUATION_SYSTEM}]},
        {
            "role": "user",
            "content": [
                {"type": "image", "image": str(image_path)},
                {"type": "text", "text": user_text},
            ],
        },
    ]


def generate_questions(generator: QwenGenerator, prompt: str, max_new_tokens: int) -> list[dict[str, str]]:
    """Extract prompt elements, then generate one yes/no question per element."""
    elements_raw = generator.generate(build_element_messages(prompt), max_new_tokens=max_new_tokens)
    elements = parse_elements(elements_raw)
    if not elements:
        raise ValueError(f"model did not return parseable elements: {elements_raw}")

    questions: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for element in elements:
        question_raw = generator.generate(build_question_messages(prompt, element), max_new_tokens=max_new_tokens)
        item = parse_single_question(question_raw, element)
        if item is None:
            continue
        key = (element.strip().lower(), item["question"].strip().lower())
        if key in seen:
            continue
        seen.add(key)
        questions.append(item)

    if not questions:
        raise ValueError("model returned no valid element/question pairs")
    return questions


def answer_questions(
    generator: QwenGenerator,
    questions: list[dict[str, str]],
    image_path: Path,
    max_new_tokens: int,
) -> tuple[list[dict], str]:
    """Score each question by visual yes-confidence (1-5) against the image."""
    raw = generator.generate(build_evaluation_messages(image_path, questions), max_new_tokens=max_new_tokens)
    parsed = parse_response_json(raw)
    payload = parsed.get("answers", parsed) if isinstance(parsed, dict) else parsed

    answers: list[dict] = []
    if isinstance(payload, list):
        for i, q in enumerate(questions):
            score = 0
            reasoning = ""
            if i < len(payload):
                item = payload[i]
                if isinstance(item, dict):
                    score = normalize_confidence_score(item.get("score", item.get("answer", "")))
                    reasoning = str(item.get("reasoning", "")).strip()
                else:
                    score = normalize_confidence_score(item)
            answers.append(
                {
                    "question": q["question"],
                    "element": q.get("element", ""),
                    "target_answer": q.get("answer", ""),
                    "reasoning": reasoning,
                    "score": score,
                }
            )
    else:
        tokens = re.findall(r"\b([1-5])\b", raw or "")
        for i, q in enumerate(questions):
            answers.append(
                {
                    "question": q["question"],
                    "element": q.get("element", ""),
                    "target_answer": q.get("answer", ""),
                    "reasoning": "Failed to parse JSON answers.",
                    "score": normalize_confidence_score(tokens[i]) if i < len(tokens) else 0,
                }
            )
    return answers, raw


def resolve_image_path(image_ref: str, images_root: Path | None, annotations_file: Path) -> Path:
    ref = Path(image_ref)
    if ref.exists():
        return ref
    candidates = [resolve_input_path(annotations_file).parent / ref]
    if images_root is not None:
        candidates.extend([images_root / ref, images_root / ref.name])
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError(f"Image not found for image_path={image_ref}")


def questions_file_for_record(record: dict, questions_dir: Path) -> Path:
    return questions_dir / f"{record.get('pair_id') or record['image_id']}.json"


def answers_file_for_record(record: dict, answers_dir: Path) -> Path:
    return answers_dir / f"{record.get('pair_id') or record['image_id']}.json"


def questions_valid(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return False
    if not isinstance(data, list) or not data:
        return False
    return all(isinstance(item, dict) and {"element", "question", "answer"}.issubset(item) for item in data)


def answers_valid(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return False
    return isinstance(data, dict) and isinstance(data.get("answers"), list)


def process_record(
    generator: QwenGenerator,
    record: dict,
    annotations_file: Path,
    images_root: Path | None,
    questions_dir: Path,
    answers_dir: Path,
    force: bool,
    max_new_tokens: int,
) -> str:
    q_path = questions_file_for_record(record, questions_dir)
    a_path = answers_file_for_record(record, answers_dir)
    if (not force) and questions_valid(q_path) and answers_valid(a_path):
        return f"skip pair_id={record['pair_id']}: already done"

    try:
        # Stage 1: prompt-only element extraction + per-element questions.
        questions = generate_questions(generator, record["prompt"], max_new_tokens)
        q_path.parent.mkdir(parents=True, exist_ok=True)
        q_path.write_text(json.dumps(questions, indent=2, ensure_ascii=False), encoding="utf-8")

        # Stage 2: score the questions against the generated image.
        image_path = resolve_image_path(record["image_path"], images_root, annotations_file)
        answers, raw = answer_questions(generator, questions, image_path, max_new_tokens)

        payload = {
            "item_key": record.get("item_key", ""),
            "pair_id": record.get("pair_id", ""),
            "text_id": record.get("text_id", ""),
            "model": record.get("model", "unknown"),
            "image_id": record.get("image_id", ""),
            "image_ref": record.get("image_path", ""),
            "image_path": str(image_path),
            "prompt": record["prompt"],
            "questions_file": str(q_path),
            "answers": answers,
            "raw_response": raw,
            "group_id": record.get("group_id", ""),
            "source_item_id": record.get("source_item_id", ""),
        }
        a_path.parent.mkdir(parents=True, exist_ok=True)
        a_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
        return f"saved {q_path.name} + {a_path.name} for prompt: {record['prompt']}"
    except Exception as exc:
        err_path = a_path.with_suffix(".error.txt")
        err_path.parent.mkdir(parents=True, exist_ok=True)
        err_path.write_text(str(exc), encoding="utf-8")
        return f"error pair_id={record.get('pair_id', '')}: {exc}"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Teacher T2IA annotation: extract elements, generate per-element yes/no questions, then score them 1-5 against the image."
    )
    parser.add_argument("--annotations-file", type=Path, default=ANNOTATIONS_FILE)
    parser.add_argument("--images-root", type=Path, default=IMAGES_ROOT)
    parser.add_argument("--questions-dir", type=Path, default=QUESTIONS_DIR)
    parser.add_argument("--answers-dir", type=Path, default=ANSWERS_DIR)
    parser.add_argument("--model", type=str, default=DEFAULT_MODEL)
    parser.add_argument("--backend", choices=("auto", "transformers", "vllm"), default="auto")
    parser.add_argument("--start-idx", type=int, default=0)
    parser.add_argument("--end-idx", type=int, default=None)
    parser.add_argument("--max-new-tokens", type=int, default=1024)
    parser.add_argument("--gpu-memory-utilization", type=float, default=0.70)
    parser.add_argument("--tensor-parallel-size", type=int, default=None)
    parser.add_argument("--temperature", type=float, default=0.0)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    annotations_file = resolve_input_path(args.annotations_file)
    records = load_annotations(annotations_file)
    total = len(records)

    start = max(0, args.start_idx)
    end = total if args.end_idx is None else min(total, args.end_idx)
    if start >= end:
        print(f"nothing to process: start={start}, end={end}, total={total}")
        return

    args.questions_dir.mkdir(parents=True, exist_ok=True)
    args.answers_dir.mkdir(parents=True, exist_ok=True)

    generator = QwenGenerator(
        args.model,
        args.backend,
        args.gpu_memory_utilization,
        args.tensor_parallel_size,
        args.temperature,
    )

    print(
        f"processing [{start}, {end}) from total={total}, one prompt at a time, "
        f"model={args.model}, backend={generator.backend}"
    )
    for idx in range(start, end):
        print(
            process_record(
                generator,
                records[idx],
                annotations_file,
                args.images_root,
                args.questions_dir,
                args.answers_dir,
                args.force,
                args.max_new_tokens,
            )
        )


if __name__ == "__main__":
    main()
